CREATE TABLE COMPANY(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  COMPANY_NAME VARCHAR(255),
  COMPANY_CONTACT_ID BIGINT
);

CREATE TABLE COMPANY_CONTACT(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CITY VARCHAR(255),
  COUNTRY VARCHAR(255),
  WWW VARCHAR(255),
  COMPANY_ID BIGINT
);

CREATE TABLE EMPLOYEE(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  DATE_OF_BIRTHDAY DATE,
  NAME VARCHAR(255),
  COMPANY_ID BIGINT
);

CREATE TABLE SKILL(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  SKILL_NAME VARCHAR(255)
);

ALTER TABLE COMPANY ADD CONSTRAINT FK_COMPANY_CONTACT FOREIGN KEY (COMPANY_CONTACT_ID) REFERENCES COMPANY_CONTACT(ID) NOCHECK;
ALTER TABLE COMPANY_CONTACT ADD CONSTRAINT FK_COMPANY_ID FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY(ID) NOCHECK;
ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_COMPANY_ID_E FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY(ID) NOCHECK;

CREATE TABLE EMPLOYEE_SKILL(
  EMPLOYEE_ID BIGINT NOT NULL,
  SKILL_ID BIGINT NOT NULL,
  FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID),
  FOREIGN KEY (SKILL_ID) REFERENCES SKILL(ID),
  PRIMARY KEY (EMPLOYEE_ID, SKILL_ID)
);


